### ISSUE TITLE
Docker bind mount permissions

### ISSUE THREAD

**Issue by endresjo** [fbngrmr/audiotheker#1]
Hi,

many thanks for sharing your code. 

Just as suggestion for your docker example. When using the docker version with your example code I get a permission error for the bind mount. Adding `--user 1000:1000` to the docker run argument solves this.

``` bash
docker run \
   --rm \
   --user 1000:1000 \
   -v "$(pwd)/download":/download \
   audiotheker:0.1.0 download \
   "https://www.ardaudiothek.de/sendung/j-r-r-tolkien-der-herr-der-ringe-fantasy-hoerspiel-klassiker/12197351/" \
   /download
```

**Comment by fbngrmr** [comment]
Hi @endresjo,

nice catch! 🏆 Thank you for pointing this out 🙂
Docker for macOS seems to normalize file permissions when using bind mounts.
I updated the Docker example so that it works on Linux and Windows as well: https://github.com/fbngrmr/audiotheker/commit/eac84c755a34ec6713c8a70ed6931eee3004b219
